import Head from "next/head";
import Image from "next/future/image";
import styles from "../styles/Home.module.css";
import Header from "../components/header";
import { useSession, getSession } from "next-auth/react";
import Hero from "../components/Hero";
import Slider from "../components/Slider";
import Companyes from "../components/Companys";
import Companyes2 from "../components/Companys copy";
import Moviescollections from "../components/Moviescollection";
import Showscollections from "../components/Showscollection";
import Top from "./../components/sectiontop";

export default function Home({
  popularMovies,
  popularShows,
  top_ratedMovies,
  top_ratedShows,
  trending_movie_week,
  trending_show_week,
  trending_movie_day,
  trending_show_day,
}) {
  const { data: session, status } = useSession();
  return (
    <div className="">
      <Head>
        <title>Disney+</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      {!session ? (
        <Hero />
      ) : (
        <main className="relative min-h-screen after:bg-home after:bg-center after:bg-cover after:bg-no-repeat after:bg-fixed after:absolute after:inset-0 after:z-[-1]">
          <Slider
            trending_movie_week={trending_movie_week}
            trending_show_week={trending_show_week}
          />
          <Companyes />
          <Companyes2 />
          <Moviescollections results={popularMovies} title="Popular Movies" />
          <Showscollections results={popularShows} title="Popular Shows" />
          <Top />
          <Moviescollections
            results={trending_movie_week}
            title="Trending movie this week"
          />
          <Showscollections
            results={trending_show_week}
            title="Trending show this week"
          />
          <Moviescollections
            results={top_ratedMovies}
            title="Top Rated Movies"
          />
          <Showscollections results={top_ratedShows} title="Top Rated Shows" />
          <Moviescollections
            results={trending_movie_day}
            title="latest movie"
          />
          <Showscollections results={trending_show_day} title="latest show" />
        </main>
      )}
    </div>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  const [
    popularMoviesRes,
    popularShowsRes,
    top_ratedMoviesRes,
    top_ratedShowsRes,
    trending_movie_weekRes,
    trending_show_weekRes,
    trending_movie_dayRes,
    trending_show_dayRes,
  ] = await Promise.all([
    fetch(
      `https://api.themoviedb.org/3/movie/popular?api_key=${process.env.TMDB_API}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/popular?api_key=${process.env.TMDB_API}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/movie/top_rated?api_key=${process.env.TMDB_API}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/tv/top_rated?api_key=${process.env.TMDB_API}&language=en-US&page=1`
    ),
    fetch(
      `https://api.themoviedb.org/3/trending/movie/week?api_key=${process.env.TMDB_API}`
    ),
    fetch(
      `https://api.themoviedb.org/3/trending/tv/week?api_key=${process.env.TMDB_API}`
    ),
    fetch(
      `https://api.themoviedb.org/3/trending/movie/day?api_key=${process.env.TMDB_API}`
    ),
    fetch(
      `https://api.themoviedb.org/3/trending/tv/day?api_key=${process.env.TMDB_API}`
    ),
  ]);
  const [
    popularMovies,
    popularShows,
    top_ratedMovies,
    top_ratedShows,
    trending_movie_week,
    trending_show_week,
    trending_movie_day,
    trending_show_day,
  ] = await Promise.all([
    popularMoviesRes.json(),
    popularShowsRes.json(),
    top_ratedMoviesRes.json(),
    top_ratedShowsRes.json(),
    trending_movie_weekRes.json(),
    trending_show_weekRes.json(),
    trending_movie_dayRes.json(),
    trending_show_dayRes.json(),
  ]);

  return {
    props: {
      session,
      popularMovies: popularMovies.results,
      popularShows: popularShows.results,
      top_ratedMovies: top_ratedMovies.results,
      top_ratedShows: top_ratedShows.results,
      trending_movie_week: trending_movie_week.results,
      trending_show_week: trending_show_week.results,
      trending_movie_day: trending_movie_day.results,
      trending_show_day: trending_show_day.results,
    },
  };
}
